"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {ArrowLeft,Minus,Plus,ShoppingBag} from "lucide-react";
import {addToCart,updateCartQuantity,cartSubtotal} from "@/lib/cart";
import type {CartItem} from "@/lib/types";
const products:CartItem[]=[
{menuItemId:"charred-pepper-prawns",name:"Charred Pepper Prawns",price:18500,quantity:1},
{menuItemId:"ember-grilled-sea-bass",name:"Ember-Grilled Sea Bass",price:32000,quantity:1},
{menuItemId:"fire-roasted-lamb",name:"Fire-Roasted Lamb",price:38500,quantity:1},
{menuItemId:"coconut-creme-brulee",name:"Coconut Crème Brûlée",price:11500,quantity:1}
];
export default function Order(){const[cart,setCart]=useState<CartItem[]>([]);useEffect(()=>{try{setCart(JSON.parse(localStorage.getItem("ember-cart")||"[]"))}catch{}},[]);useEffect(()=>{localStorage.setItem("ember-cart",JSON.stringify(cart))},[cart]);const add=(item:CartItem)=>setCart(c=>addToCart(c,item));const change=(id:string,q:number)=>setCart(c=>updateCartQuantity(c,id,q));return <main className="min-h-screen bg-[#f5f0e6]"><header className="border-b border-black/10 px-5 py-6"><div className="mx-auto flex max-w-7xl justify-between"><Link href="/" className="serif tracking-[.2em]">EMBER & IVORY</Link><Link href="/cart" className="text-xs uppercase tracking-[.15em]">Cart ({cart.reduce((n,i)=>n+i.quantity,0)})</Link></div></header><div className="mx-auto grid max-w-7xl gap-12 px-5 py-16 lg:grid-cols-[1fr_360px]"><div><Link href="/" className="flex items-center gap-2 text-xs uppercase tracking-[.15em]"><ArrowLeft size={14}/> Back</Link><h1 className="serif mt-12 text-6xl">Order from the kitchen.</h1><div className="mt-12 grid gap-5 md:grid-cols-2">{products.map(item=><article key={item.menuItemId} className="border border-black/10 bg-white/30 p-6"><p className="text-xs uppercase tracking-[.2em] text-[#b9572b]">Featured</p><h2 className="serif mt-3 text-2xl">{item.name}</h2><div className="mt-6 flex items-center justify-between"><span>₦{item.price.toLocaleString()}</span><button type="button" onClick={()=>add(item)} className="bg-[#171513] px-4 py-3 text-xs uppercase tracking-[.15em] text-white">Add</button></div></article>)}</div></div><aside className="h-fit bg-[#171513] p-7 text-[#f5f0e6] lg:sticky lg:top-8"><div className="flex items-center gap-3"><ShoppingBag size={18}/><h2 className="serif text-2xl">Your order</h2></div><div className="mt-7 space-y-5">{cart.map(item=><div className="border-b border-white/10 pb-4" key={item.menuItemId}><div className="text-sm">{item.name}</div><div className="mt-2 flex items-center gap-3"><button type="button" onClick={()=>change(item.menuItemId,item.quantity-1)}><Minus size={14}/></button><span>{item.quantity}</span><button type="button" onClick={()=>change(item.menuItemId,item.quantity+1)}><Plus size={14}/></button></div></div>)}</div><div className="mt-6 flex justify-between text-sm"><span>Subtotal</span><span>₦{cartSubtotal(cart).toLocaleString()}</span></div><Link href="/checkout" className="mt-8 block bg-[#b9572b] px-5 py-4 text-center text-xs uppercase tracking-[.18em]">Continue to Checkout</Link></aside></div></main>}